### PR TITLE
OH-58D Radio Updates

### PR DESCRIPTION
**Pull request by victrox-dev**
- Fix Transmit Selector Switch RMT functionality
- Added CIPHER; CNV based on channel number
- Added FM Retrans capability; RX only during retrans

### CODE REVIEW

**Comment by LazyBoot** [comment]
Is it intended that encryption doesn't work on VHF?

**Comment by victrox-dev** [comment]
> Is it intended that encryption doesn't work on VHF?

It is intended. Although the aircraft lets you do it, and the -10 TM for the aircraft does talk about loading COMSEC for the UHF and VHF radios, I think for the purpose of SRS/DCS it's a moot point because (as far as I'm aware) there are few (if any) aircraft that SRS permits VHF encryption for. Including AWACS radios; at least by default none of the VHF-AM radios in the AWACS panel even support VHF encryption. So I guess my point is, who are you even going to talk to?

Likewise, VHF encryption is so rare in the real world (at least in the Army) that I've never even heard of it being done.

I'm not opposed to implementing it, but I've performed a precursory search of SRS code to see if any aircraft support VHF-AM encryption and I can't find any that do.

Perhaps Ciribob will have some input on the matter.

**Comment by LazyBoot** [comment]
After some quick testing A-10c2, F-14, F-16 and F/A-18 all allow encryption on VHF. Other than those I only tested the F-15E, but that one doesn't seem to have working crypto at all in DCS.

**Comment by victrox-dev** [comment]
Noted. I will implement it based on those aircraft having the capability.
I'm going to look into one other thing before I push a commit for that.

**Comment by ciribob** [comment]
Im just going to add the channel to the SRS overlay (if its in channel mode) and then release

Thank again @victrox-dev !

**Pull request merged**
