### PR TITLE
Allow Combat Arms and External EAM mode Intercom communication.

### PR DESCRIPTION
**Pull request by TaeruAlethea**
Send update is now has better awareness of Multiseat aircraft and Combined Arms Units.

### CODE REVIEW

**Comment by ciribob** [comment]
Sorry can you explain this a little more?

Adding the special slot types here will likely cause a conflict with the Export environment and the slot wont ID wont be parsed or synced on the C# side

**Comment by TaeruAlethea** [comment]
With these additional fields, downstream components could identify all Blue coalition "Game Masters" and place them into a single Intercom instance or similar items.

When testing locally and on a live online server with other users, I did not see any errors or obvious conflicts. There were no DCS errors observed either. The existing values stay the same as previously configured, however there are now fields that can be accessed to identify Special slot types.

The DCS API query is the same as the previous implementation. Only additional parsing is being done.
Is there a downstream impact that was not obvious?

**Comment by TaeruAlethea** [comment]
Adjusted the Lua to now set a unit value based on what the next type is. 
The Text type name is the only spot to identify CA roles.

**Comment by TaeruAlethea** [comment]
Cases tested:
1: ✅ Blue EAM <-> Spectator, Exp: No Comms
2: ✅ Blue EAM <-> Blue Controller, Exp: Working
3: ✅ Blue EAM, Intercom Ch1 <-> Blue Controller, Intercom Ch2, Exp: No Comms
4: ✅ Blue EAM, Intercom Ch2 <-> Blue Controller, Intercom Ch1, Exp: No Comms
5: ✅ Blue EAM <-> Red Controller, Exp: No Comms, Exp: No Comms

**Comment by TaeruAlethea** [comment]
Combined Arms and EAM now support intercom and Intercom channels.

**Comment by TaeruAlethea** [comment]
Superseded by #724.

**Pull request closed without merging**
