### PR TITLE
added "DarkMode" option, enabled by default, can be disabled in "Settings".

### PR DESCRIPTION
**Pull request by Dani3lNL20**

### CODE REVIEW

**Comment by Dani3lNL20** [comment]
just noticed, it doesn't save "white" (#ffffff) setting if SRS is closed and restarted, so that needs to be added asap

**Comment by Dani3lNL20** [comment]
Also no idea why it says 6 commits, should only be 3, only 3 files were changed.

**Comment by ciribob** [comment]
You seem to have changed the spacing a lot in the Global settings file?

As you said, the setting doesnt apply on startup (which ever you've picked)

Colour helper should be in some util helper functions somewhere

**Comment by ciribob** [comment]
Closing for now due to conflicts - please re-open once comments and conflicts are addressed

**Comment by Dani3lNL20** [comment]
I managed to get it to save (on restart) whether the button was set to on or off, but the color doesn't change along with it -.-

**Pull request closed without merging**
