### PR TITLE
Tweaked M-2000C IFF-Transponder code

### PR DESCRIPTION
**Pull request by mobot-gh**
Hi ciribob,

I did some digging on transponder modes and codes and cross-referenced as many sources as possible including an image search for cockpits with the NRAI-7A transponder and the weight of evidence points to mode 1 being a 5-bit number, so only values from 0-7 on first drum and 0-3 on second drum would be valid. Evidence also points to mode 3A being a 4 digit octal number so drums set to 8 or 9 could be clamped to 7 as I have suggested here.

I also set mode 4 to always on as the cockpit control is non-functional in 2.5.5.

The IDENT switch also has the MIC setting similar to the Huey and A-10C but as the Mirage is set to partial HOTAS control for the radio as of 2.5.5 I'm not sure if the switch on the throttle is 'wired' up to act as ptt in the same way as the MIC-DOWN control on the Huey or A-10C.

Cheers,

mobot

### CODE REVIEW

**Comment by gyrovague** [comment]
> weight of evidence points to mode 1 being a 5-bit number, so only values from 0-7 on first drum and 0-3 on second drum would be valid. Evidence also points to mode 3A being a 4 digit octal number so drums set to 8 or 9 could be clamped to 7 as I have suggested here.

Correct, F-14 and A-10C also have it implemented this way in cockpit anims:  Mode 1 is a 5bit code with 0-7 on first drum and 0-3 on second, and mode 3/A is a 12bit code with 0-7 on all 4 drums.

**Comment by ciribob** [comment]
The IDENT switch is supposed to be three position, IDENT, OFF and MIC, but unfortunately only two so MIC is inaccessible

Why have you removed the EMERG mode for the transponder?

Correct on the codes, I hadn't noticed it went higher than it should so thanks for that.

Mode 4 - I hooked up to that button just so it wasn't always on to give some control, as the correct button isn't currently modelled

**Comment by mobot-gh** [comment]
>
> The IDENT switch is supposed to be three position, IDENT, OFF and MIC, but unfortunately only two so MIC is inaccessible
> 
Understood.

> Why have you removed the EMERG mode for the transponder?
> 

I failed to grasp that iffPower being assigned the value 4 is probably some sort of failure state and doesn't rely solely on a cockpit switch. Reverted.

> Correct on the codes, I hadn't noticed it went higher than it should so thanks for that.
> 
> Mode 4 - I hooked up to that button just so it wasn't always on to give some control, as the correct button isn't currently modelled

Understood. Reverted.

**Comment by ciribob** [comment]
Thank you! 👍 Will merge

**Pull request merged**
