### PR TITLE
Connecting fix

### PR DESCRIPTION
**Pull request by ciribob**

### CODE REVIEW

**Comment by giupo** [comment]
Will this give feedback to the client when the server is offline?

**Comment by MorpheusXAUT** [comment]
This PR only included a fix for an issue causing SRS to get "stuck" in the `Connecting` state under certain circumstances.
The `Server` and `VOIP` connection status indicators will turn red though if no connection can be made to the selected servers, although SRS cannot distinguish between a server that's offline and one that simply hasn't opened their firewall properly or likewise.

**Comment by giupo** [comment]
Thank you @MorpheusXAUT , I was looking for a fix for 1.5.4.0: when I press connect, and I'm sure the server is offline, I don't receive any sort of feedback, should I open an issue?

**Comment by MorpheusXAUT** [comment]
If you still experience this issue with `1.5.4.0`, please do - the changes merged above and released in `1.5.4.0` should've fixed that issue. If you can, please also add the server/address you tried and reproduced the issue with.

**Pull request merged**
