### PR TITLE
Alternative auto ip lookup for dcs autoconnect

### PR DESCRIPTION
**Pull request by HappyGnome**
Hi I've made a small change to DCS-SRS-AutoConnectGameGUI.lua to fix auto IP acquisition when SERVER_SRS_HOST_AUTO == true. Instead of using DCSWeb, we make a call to ipv4.icanhazip.com via socket.http module shipped with DCS (assuming DCSWeb was the original issue).

### CODE REVIEW

**Comment by ciribob** [comment]
Looks great! Are there any limits or usage issues with that web service?

**Comment by HappyGnome** [comment]
No problem, I fixed this for the server I'm part of and thought it might be worth sharing.

I don't believe there are limits (at least none to affect calling it once per server per mission), no API key is required. I can't find much about it, except that it's been popular for many years, and since 2021 is run by Cloudflare.

Here's a blog from the original creator: https://major.io/2021/06/06/a-new-future-for-icanhazip/

**Comment by ciribob** [comment]
Thank you for the great read! I used both slicehost and rackspace as well back in the day.

Definitely happy with this then.

I'll merge and add to the next release

**Comment by HappyGnome** [comment]
My pleasure, glad this is useful!

**Comment by ciribob** [comment]
Thanks again!

**Pull request merged**
