### PR TITLE
Enhanced MIDS compatibility

### PR DESCRIPTION
**Pull request by TaeruAlethea**
Added MIDS Presets.
Enabled Rotary Button navigation for MIDS.

### CODE REVIEW

**Comment by TaeruAlethea** [comment]
Bump

**Comment by TaeruAlethea** [comment]
Bump

**Comment by ciribob** [comment]
Thanks for this - i'm going to decline this PR but I have used parts of it to add support now

The options now are:

Create a file like so:  HOME2|125
125 is the MIDS channel and it'll calculate the frequency

OR

if no file is present (or the entries invalid) it'll generate 1-125 as usable channels

**Comment by ciribob** [comment]
https://github.com/ciribob/DCS-SimpleRadioStandalone/pull/707 for details

**Pull request closed without merging**
