### PR TITLE
Add support for F-14 IFF panel.

### PR DESCRIPTION
**Pull request by gyrovague**
Preliminary code for F-14 IFF panel.  ~This is untested, please test first.~ Lightly tested, switches and codes seem to reflect correctly on SRS overlay.

### CODE REVIEW

**Comment by gyrovague** [comment]
This has now been _lightly_ tested, seems to work.


Screen_200217_225931

**Comment by ciribob** [comment]
Thank you very much!

Is there some way of knowing using the export if anyone is in the backseat?

If in MP no one is I'd like the pilot to be able to use the SRS overlay as otherwise they can't set them - unless jester can?

Also for the viggen - where's the best place to report a bug? Can I PM you on Discord?

**Comment by gyrovague** [comment]
Hmm, I'll have to think about that for MP, it's too late to add anything now for the next OB tomorrow.

Regarding Viggen, I asked and they said best place to report bugs is "forum bug section on ed forums". I'll see if I can find you on one of the discord channels I'm on, and ping you regardless.

**Comment by gyrovague** [comment]
Similarly, not sure how it would work exactly in MP when both seats have human players. Will both send transponder codes? Or only RIO?  FWIW I don't think these transponder switches are synced from back to front seat in multicrew currently (since they were never functional before), so front seat may well have wrong values compare to what human RIO sets them.

**Comment by ciribob** [comment]
If I can detect if its occupied - I'd disable the transponder if someone was in the rear seat so there isnt a conflict - can send a flag so DArt knows to go with the rear seat one 

For the rear one though I'd also have to detect that you're sitting in the rear seat so this is getting tricky :D

**Comment by gyrovague** [comment]
I'm also not currently sure how to distinguish between multiplayer pilot with no RIO, and singleplayer pilot.  For the former one would want the overlay, but for the latter probably not (since he can hop into the back seat to set those).

Maybe one idea is to have SRS have a keybind for toggling overlay override. That way anybody in any seat, whether SP or MP can opt to use the jet controls (if possible) or the overlay (as desired, or when not possible in jet).

**Comment by ciribob** [comment]
I can determine Multiplayer Vs single player using other logic from the gamegui so that's ok

**Comment by ciribob** [comment]
Will add switch to the profile to always enable the Overlay controls as a first pass

**Pull request merged**
