### PR TITLE
Fix broken display IDs for AH-64D causing selected radio detection not working

### PR DESCRIPTION
**Pull request by FalcoGer**
Fixes broken display IDs for AH-64.
Currently CPG radio selection is the one used by the PLT, and CPG is stuck on radio 1.
ED's latest patch broke display IDs.

### CODE REVIEW

**Comment by FalcoGer** [comment]
After figuring out how to test it, it now works as expected.
Tested all volume knobs (master, sens, 5 radios), ident, emergency xpndr, emergency grd, guard, RTS and xpndr set (M1, M3, M4, standby/norm, standby + emerg) for both crew stations and everything seems to be working.

**Comment by ciribob** [comment]
Thanks for this!

**Comment by ciribob** [comment]
Ah found an issue - if you do a cold start you get errors for a while until its finished starting @FalcoGer 

Could you try from a cold start, then do autostart and check?

**Comment by ciribob** [comment]
I'll also test with the old script to see if the bug is there too

**Pull request merged**
