### PR TITLE
Fix SERVER_SRS_HOST_AUTO (Attempt 2)

### PR DESCRIPTION
**Pull request by Camble**
Original PR: #676 This fixes the SERVER_SRS_HOST_AUTO by making use of net.get_server_host() on the client-side.

@ciribob  MESSAGE_PATTERN_OLD & MESSAGE_PATTERN_OLDER should now match to obtain the host where no `:PORT` has been specified.

I've updated the auto-connect message to only send the port if SERVER_SRS_HOST_AUTO is enabled, otherwise it uses the original message with SERVER_SRS_HOST and SERVER_SRS_PORT.

I've removed the isAutoConnectMessage function in favour of regex matching. We try to get the port from the message, if this fails, fallback to matching on IP and Port.

### CODE REVIEW

**Comment by ciribob** [comment]
Thanks for this! As im in a rush for the Apache fix I wont include this as I dont have time to test but i'll add to the next release

this looks great :)

**Comment by Camble** [comment]
Nice one, thanks. No rush. Sorry it took so long to revisit. I don't have access to your test suite or I'd double check everything. Might be worth checking before merging though. Let me know if it needs any tweaks!

**Comment by ciribob** [comment]
Finally had a bit of time to look at this - i'd still have an override option for configuring the IP as in some cases the IP isnt the same as the DCS host machine. I'd also have an optional one as well for still showing the IP and Port for users that want it (if people have disabled autoconnect)

Then it can in effect be :
- current behaviour (default)
- Your new behaviour with a much smaller message and an nice auto IP feature

**Comment by Camble** [comment]
So I poached `SERVER_SRS_HOST_AUTO` as it wasn't working. I left the existing behaviour in place if this is false. I may be missing something, but this should allow the message to be constructed using `SERVER_SRS_PORT` and `SERVER_SRS_HOST`.

Default behaviour is [here](https://github.com/ciribob/DCS-SimpleRadioStandalone/pull/715/files#diff-d445f4594157f95f01d39c6c05314f647b31cf6386670872fa77de262f01952fR76).

**Comment by ciribob** [comment]
Sorry for being so slow on this - i'll have a test and get in the next release. Thanks!

**Pull request merged**
