### PR TITLE
Allow device changes while connected

### PR DESCRIPTION
**Pull request by wokket**
Hey mate,

I'm opening this up now to make sure you're happy with the general approach I'm taking.  There's two real functional changes in here:
- Allowing a user to change the selected Mic/Output etc device while connected to a server (the request in #505)
- Detecting changes in the available hardware in real time (allowing me to plug my headset in and use it without restarting the client)

The first item is looking pretty good so far.  The second looks to be working, but actually _using_ the freshly plugged in device is throwing some low-level errors on me which I can't tell are related to this change globally, my device, my PC etc etc

If you'd like these split into to two PR's, or anything else let me know 👍

### CODE REVIEW

**Comment by wokket** [comment]
@ciribob Just wondering if you've had a chance to look at this mate?

**Comment by ciribob** [comment]
Sorry I thought I'd replied! 

Let me take another look on the weekend.


Hassle me if I don't!

**Comment by ciribob** [comment]
Finally had a look - looks like a sensible approach. You can approach it even more naively but in effect doing the connect / disconnect cycle again, which it looks like you're starting to do.

The only risk is for FC3 aircraft / non cockpit ones, the current state is lost but thats easy enough to save and then restore after the async disconnect and reconnect

**Comment by ciribob** [comment]
Closing for now - feel free to reopen @wokket if you continue to work on it

**Pull request closed without merging**
