### PR TITLE
[FEATURE] F15E hot mic

### LINKED ISSUE #663: [Feature Request] Intercom hot mic support for F-15e
According to the F-15E manual, the intercom has 3 settings based on the MIC 3-way switch in the left console:
RAD ORIDE: attenuate radio comms in favour of intercom communication. Warning messages are not overridden.
ON: Direct communication from the cockpit in which it is selected with the other cockpit and/or ground crew (i.e front/rear both set this on and it should continuously transmit)
OFF: turns of mic for intercom purposes but can still operate radios.

TL;DR: There is no switch for transmitting over the intercom, it's either always transmitting or not. Can we please get support for this in the streagle?

### PR DESCRIPTION
**Pull request by NiklasMerz**
**I could not successfully test this yet! Appreciate any pointers what's missing**

I think the Strike Eagle is missing a hot mic for the intercom. RAZBAMs documentation says:

>Intercom Function Selector Switch. It is spring-loaded to ON position. RAD 
ORIDE overrides the radio comms in favour of the intercom. In ON it provides direct 
communications between crew members. OFF turns off the microphone for intercom 
purposes (but not for radio)
> (Page 78)

I understand from this that setting MIC to ON should have a hot mic for WSO and pilot?

I started working on this and the button is now correctly identified but the Intercom is not switching to hot mic mode like in the Apache. I looked in the Apache code and it should work with these changes. **What am I missing?**

Closes #663

### CODE REVIEW

**Comment by NiklasMerz** [comment]
I made these changes in the scripts of my DCS install. Do I need to do something else to get this working?

Thanks for the help.

**Comment by ciribob** [comment]
The hot mic won't work unless the aircraft is set to use DCS cockpit controls 

For this to work - the mic switches must be animated. I can see front seat now is animated - but I was unable to check the back seat in multiplayer

If you can confirm the mic switch moves (either DCS VOIP controls or DCS Radio controls) then hot mic can be added to the F15 as those keybinds can be used

**Comment by NiklasMerz** [comment]
I just tried the back seat again and it looks like the buttons don't have an animation, yet. So we would need to wait for the animation to get this working? The bindings are there. 

What do I need to add to the script to get hot mic from front to back working at least?

**Comment by ciribob** [comment]
You'll have to change the control flag 

For example: https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/master/Scripts/DCS-SRS/Scripts/DCS-SimpleRadioStandalone.lua#L5091

Set it to 1 for In Cockpit controls (for the front seat) and 0 for SRS controls

The hotmic will only work if the controls are set to cockpit (to avoid SRS users hot mic-ing)

**Comment by abesl-pi** [comment]
works greats! finally hotmic :)

**Comment by NiklasMerz** [comment]
Thanks @ciribob that did the trick. I just tested it with a WSO on a multiplayer server and it works just fine with hot mic and the mic switch for pilot and WSO.

**Comment by ciribob** [comment]
Great! Glad thats works.

Im not sure about including this as it means the WSO and the Pilot have different controls and behaviours so i'd rather wait until the animations are there and it can be consistent


If you (or others!) disagree - feel free to comment

**Comment by NiklasMerz** [comment]
I'm not sure what you mean by different controls and animations. Both pilot and WSO have an intercom mic switch with 3 positions. If you flip it to ON the hot mic is on. The switch is animated in both cockpits.

**Comment by ciribob** [comment]
Sorry I mean the VOIP controls - the front seat has animations so the DCS VoIP controls can be used, however the back seat cannot as the animations aren't on the stick in the rear

**Comment by NiklasMerz** [comment]
Sorry but I still don't fully get it. The backseat throttle buttons are not animated that's right. In my test this wasn't a problem for us. We both turned the mic switch in the left console to ON and could use the hot mic. With the switch to OFF it works as usual.

I hope this works as expected and you or somebody else can test this successfully with two people in one jet.

**Comment by ciribob** [comment]
Sorry for the slow reply - and how did you switch radios in the back out of intercom? I'd have thought you'd be stuck and couldnt switch

**Comment by NiklasMerz** [comment]
If I turn the Intercom Mic switch to the ON hot mic is enabled.
Switching it to OFF disables it again. This worked in the front and back
seat in our test. The 3 position intercom mic switch is animated front
and back and seems to work fine with DCS BIOS.

I hope you or someone else can confirm my change works.

**Comment by ciribob** [comment]
Sorry but did the radio controls also work in the back? Not just intercom - but being able to select and use the radios as well?

**Comment by abesl-pi** [comment]
we just tested it another time. everything works fine. intercom and push2talk and radios in both seats work. please merge, many people are waiting for f15e hotmic for intercom

**Comment by NiklasMerz** [comment]
I was the WSO for @abesl-pi. We could not find any issues with the hot mic. Talking on the radio worked just like before.

**Pull request merged**
