### PR TITLE
Added Backup UHF controls for F16 + Updated AutoConnect

### PR DESCRIPTION
**Pull request by Raffson**
I expanded the F16 code to add support for the UHF's backup controls.
Aside from that I updated the AutoConnect script so it automatically detects the external IP. This makes it easier for people who wish to host a temporary server and fly with some friends. In order for this to work, a folder called "socket" must be made within "DCS-install-folder/LuaSocket". Both http.lua and url.lua (located in "LuaSocket") should be copied into that "socket" folder, otherwise the http-module won't be found. In order to make sure this folder is present, I adjusted the installer so it will copy those files if they're not present, though I'm not sure if what I did will work so I would like to ask if you can verify that my adjustments wrt to the installer are correct.

### CODE REVIEW

**Comment by Raffson** [comment]
Appologies for the Lua files that kind of got messed up, I suspect it's due to the fact that I was working with those files on a different computer and then just replaced them 🤬

**Comment by bubblefrog** [comment]
The backup controls should already be working in my original PR, it's implemented internally in the module. Switching C&I to backup will give "UHF backup control" the control of the UHF radio. From SRS it will look the same, the UHF device defined in the module will change frequency according to the backup controls. Worth noting is that the UHF radio cannot go lower than 225 MHz, so the backup controls need to be configured for a frequency higher than 225 for it to be able to change the frequency of the radio.

**Comment by Raffson** [comment]
> The backup controls should already be working in my original PR, it's implemented internally in the module. Switching C&I to backup will give "UHF backup control" the control of the UHF radio. From SRS it will look the same, the UHF device defined in the module will change frequency according to the backup controls. Worth noting is that the UHF radio cannot go lower than 225 MHz, so the backup controls need to be configured for a frequency higher than 225 for it to be able to change the frequency of the radio.

Have you specifically tested this cause iirc I tried this yesterday but if I don't define what needs to happen, nothing changes when using backup UHF controls.. I'd gladly test it again in a couple of hours, but if what you're saying is true, then I should close this pull request and make a new one for my changes to AutoConnect. I also noticed that the code I added in the installer is incomplete, i.e. I forgot to create the "socket" folder if it doesn't exist.

**Comment by bubblefrog** [comment]
> > The backup controls should already be working in my original PR, it's implemented internally in the module. Switching C&I to backup will give "UHF backup control" the control of the UHF radio. From SRS it will look the same, the UHF device defined in the module will change frequency according to the backup controls. Worth noting is that the UHF radio cannot go lower than 225 MHz, so the backup controls need to be configured for a frequency higher than 225 for it to be able to change the frequency of the radio.
> 
> Have you specifically tested this cause iirc I tried this yesterday but if I don't define what needs to happen, nothing changes when using backup UHF controls.. I'd gladly test it again in a couple of hours, but if what you're saying is true, then I should close this pull request and make a new one for my changes to AutoConnect. I also noticed that the code I added in the installer is incomplete, i.e. I forgot to create the "socket" folder if it doesn't exist.

I tested it an extra time just to be sure and it seems to be working. The problem is that the backup radio controls allow you to configure the radio outside the specification of the AN/ARC-164. If you configure a frequency on backup control panel lower than 225 Mhz nothing will change, but if you set the frequency above that it should work. Just let me know it the problem still exists when testing it again.

**Comment by Raffson** [comment]
> > > The backup controls should already be working in my original PR, it's implemented internally in the module. Switching C&I to backup will give "UHF backup control" the control of the UHF radio. From SRS it will look the same, the UHF device defined in the module will change frequency according to the backup controls. Worth noting is that the UHF radio cannot go lower than 225 MHz, so the backup controls need to be configured for a frequency higher than 225 for it to be able to change the frequency of the radio.
> > 
> > 
> > Have you specifically tested this cause iirc I tried this yesterday but if I don't define what needs to happen, nothing changes when using backup UHF controls.. I'd gladly test it again in a couple of hours, but if what you're saying is true, then I should close this pull request and make a new one for my changes to AutoConnect. I also noticed that the code I added in the installer is incomplete, i.e. I forgot to create the "socket" folder if it doesn't exist.
> 
> I tested it an extra time just to be sure and it seems to be working. The problem is that the backup radio controls allow you to configure the radio outside the specification of the AN/ARC-164. If you configure a frequency on backup control panel lower than 225 Mhz nothing will change, but if you set the frequency above that it should work. Just let me know it the problem still exists when testing it again.

Copy that! Will verify later and adjust where needed 👍

**Comment by Raffson** [comment]
Ok so it turns out not everything's working if i leave out my code.. specifically the volume ought to be controlled through the backup panel which isn't happening right now and aside from that if you set the function to both, the radio is not listening to the guard frequency.. i guess i'll have to make a couple of adjustments in order to get it right..

**Comment by ciribob** [comment]
You dont need to copy the files - you should be able to access the DCS ones as long as you get the include path correct - exactly as I access the socket library in the GameGUI already. 

I'd also prefer not to create a dependency like this and for dedicated servers there may well be multiple IPs depending on the hosting setup so you wont necessarily get the correct one when trying to work out the public IP

There are also solutions like https://www.noip.com/free that fulfil this for you - and are often built into home routers if you're hosting at home

As there is also another pull request for the F16 im going to close this for now. The backup UFC panel is also unneeded (in theory) as DCS has the frequency directly stored in the "radio" interface  - so no need to figure out switch positions

Thank you for the PR though - its funny how a whole bunch have suddenly appeared!

**Pull request closed without merging**
