### PR TITLE
Updated Export Radio for A-4E

### PR DESCRIPTION
**Pull request by 08jne01**
Changed:
- Checks the uhf_radio device to see if there is power.
- Function Select switch only checked to see if dual guard + radio is
required.
- Mode select is no longer required since the frequency is now just
fetched from the uhf_radio device.
- Channel just permenantly set to nil since there is no way for none
official modules to make use of the radio channels. (Channels can still
be emulated within another device).

### CODE REVIEW

**Review by ciribob — COMMENTED** [review]
When you say channels dont work - do you mean if you set the radio to channel mode and radio wont follow the channels at all?

**Comment by 08jne01** [comment]
> When you say channels dont work - do you mean if you set the radio to channel mode and radio wont follow the channels at all?
> 
> Which version of the A-4E should I test SRS against ? Latest Dev branch one?

Yea the :set_channel for the lua radio device does not work. There is no way for us to alter the lua device such that you could read the channels anyway. A workaround would be to set an animation arg.

**Comment by ciribob** [comment]
Ah ok, you can use set frequency though, that works? As long as you know the frequency of the fixed channel you can set it.

Unsure if you do know the channel frequency though?

**Comment by 08jne01** [comment]
> Ah ok, you can use set frequency though, that works? As long as you know the frequency of the fixed channel you can set it.
> 
> Unsure if you do know the channel frequency though?
> 
> For SRS, I just read the animation arg from the channel selector, that gives me the channel number. I would normally read the mode selector too to figure out if it's in channel mode or not

Ah yea, I removed the channel code. I should probably put that back so you can see the channel from that selector.

For the frequencies the channels are retrieved from the mission and the frequency is set as appropriate so the channels do work. So only get_frequency is required.

**Pull request merged**
