### PR TITLE
Added axis assign options

### PR DESCRIPTION
**Pull request by JurgenvRooyen**
Implemented basic axis assign options, accessible to users in the client via a new button labelled axis and works for both device axes and sliders. 

I have limited hardware to test on but it worked fine with both my throttle and flight stick.

Currently when setting the axis, the initial position is considered the resting/neutral position and any difference of value > 10,000 activates the axis as a binding.

### CODE REVIEW

**Comment by JurgenvRooyen** [comment]
Closing for the time being - refactoring this feature and adding to it.

**Comment by JurgenvRooyen** [comment]
Improved the axis assign to work like as an actual axis, with assigns to radio (and intercom) volume, radio frequency and radio encryption.

Added options to adjust axis curvature and invert outputs for an assigned axis (though as of now this doesn't visualise the current axis position, only the sigmoid curve for all positions). 

Its possible that the frequency axis assignments should be split into an assignment for the MHz and Hz portions but as above I have limited hardware to test on so I left this for now pending review or feedback.

**Comment by ciribob** [comment]
I've rolled this PR back from master while doing some testing - I cant figure out why but if you compare

https://github.com/ciribob/DCS-SimpleRadioStandalone/commit/dcd09ed87a5074bd05f47cc2cadbbb60c0a11efd

with the latest master - you'll see the CPU jump hugely when SRS is connected

I tried commenting out big chunks of the device polling to see if its axis reading - which didnt seem to make much difference. I also cant see anything obvious on the CPU profiler

Its not the recording branch - as that works fine and shuts down if you've not enabled it

Would you be able to see whats up CPU wise?

**Comment by JurgenvRooyen** [comment]
Just checked real quick, I'm not seeing high CPU usage. Profiler results aren't showing a spike on my machine either. Though the constant polling does have an effect on the window rendering now that I'm paying attention, the volume slider bar stutters.

I assume you were seeing the CPU thrashing in the merged release candidate?

Also, I noticed I had completely overlooked the final commit and push apparently. The merged```GetAxisValue``` function will never return a curvature adjusted value, so its for the best rollback happened.

**Pull request merged**
