### PR TITLE
Gamepad inputs while in background (XInput)

### PR DESCRIPTION
**Pull request by gcask**
Using XInput allows SRS to read gamepad (at least Xbox/xbox compatible ones) while the game is in the foreground and SRS is in the background.

Added a setting to enable/disable (default disabled), since this is pretty niche.

Checked with a HOTAS and an Xbox gamepad plugged in - only the Xbox gamepad generates XInput data.

### CODE REVIEW

**Comment by gcask** [comment]
Screenshot of new setting and display:
image
image

**Comment by ciribob** [comment]
Thanks for this! Sorry I'll review and merge for the next big 2.8.X release 

Out of interest - why wouldnt I want to have this always enabled? I'm guessing I can whitelist the specific xbox devices so as you've done it looks like it should be OK to have always there?

How did you test this? Bluetooth Xbox One controller? 

I've got an old wired 360 controller and an Xbox One controller so I think I can test

**Comment by gcask** [comment]
Absolutely no worries :)

My main concern was overall devices compatibility and other shenanigans... I think DCS users have a *broad* ranges of devices, and having this disabled by default or at least as an option felt like the safest bet to avoid mayhem for some users, as there might the odd device around.

Especially since gamepad players are seldom (allegedly).

I agree it *should* be ok... This just seemed safest :)

I've tested this with a plugged in XBox One controller.

I've been using it regularly now (I'm currently on the move with a gamepad-only setup), and it's been very reliable!

**Comment by ciribob** [comment]
Makes sense! I'll merge as is and do some more testing and see if I can remove the option later on (so its always on)

Thanks for the PR!

**Pull request merged**
