### PR TITLE
Hercules mod support

### PR DESCRIPTION
**Pull request by gcask**
* Working in-game UHF radio
* Working cockpit volume control
* Additional VHF expansion radios.

### CODE REVIEW

**Comment by ciribob** [comment]
Thanks for this! Surprised the radio is working internally

Please can you mark

```_data.radios[3].expansion = false```

Though? 

Might as well make them non expansion as it has more radios before, and there are more in the cockpit (they're just not usable)

**Comment by gcask** [comment]
Yeah that's why I marked them as expansion, since they have no cockpit control (through the MFD or other).

The radio absolutely works from the cockpit, you can change it by hand or use the channel presets.
Here's a quick vid highlighting the power up working, and switch the radio via preset (proof!)

https://user-images.githubusercontent.com/53709079/227549107-86ef3a0c-f32c-400f-b26f-474196a805b6.mp4

**Comment by ciribob** [comment]
Ah sorry what that flag does is if the server has "expansion radios" disabled - you'll lose some radios.

If you set that to false you'll always have these radios (as it currently does) but the controls on the overlay or via hotkeys will still work

**Comment by gcask** [comment]
Ah, I see thanks! That makes total sense there.

Should be updated!

**Comment by ciribob** [comment]
Thanks! I'll add this into the next release 👍 

Really appreciate this!

**Pull request merged**
