### PR TITLE
SA342 radio selectors

### PR DESCRIPTION
**Pull request by LazyBoot**
This should get the radio selctors in the gazelle working.

### CODE REVIEW

**Comment by ciribob** [comment]
Ah ok, I'll have a think, there isn't really a way for a hybrid of controls and dcs for selection but can add something

**Comment by gyrovague** [comment]
I agree that it might be useful (in general, irrespective of SA342) to have an SRS option or feature to have SRS controls for radio and intercom PTT to be able to override or augment cockpit controls. We've had feedback on F-14 that some prefer using SRS controls even when the aircraft has dedicated bindable controls for all radio&intercom inputs.

**Comment by LazyBoot** [comment]
How about making an option in the settings page where you can choose "use SRS controls" or "use cockpit controls where available"? And just have that as a global option.

**Comment by ciribob** [comment]
I can just have a flat override option for the radio selector so hotkeys always work - thats the easiest change - but then that means the incockpit selector of this pull request wont work!

Perhaps always allowing the hotkey for intercom is the way but thats more tricky to do -need to check both the ptt isn't held and the hotkey for switching isn't held

**Comment by ciribob** [comment]
Not forgotten - will work on this new control type in the next release :)

**Comment by ciribob** [comment]
Thanks for this - Made some changes to how the gazelle is integrated with SRS - going to close this pull request now but your changes on the radio side are now in #394 Pull request 

There will now be a hotmic for the intercom all the time but that can be changed by changing the SRS Control settings

**Pull request closed without merging**
