### PR TITLE
Ip address book

### PR DESCRIPTION
**Pull request by GylesBates**
Hey, so i have something working but i think we need to test the auto-connect feature. I'm not going to be around till tuesday now (i can read mails though).

Some things off top of my head:

- I edited some of the projects to make sure it loads as 64 bit in debug
- I upgraded one of the nuget dependencies as it looks like you had done
- I've put in code to help the "migration" from old settings to new.
- I've not paid much attention to styling

Let me know what you think.

### CODE REVIEW

**Comment by ciribob** [comment]
Ah great thanks! That's was very quick work!

Ill hopefully have time Friday to have a look and possibly do a release as well.

Will test autoconnect 

Thanks again! 👍

**Comment by ciribob** [comment]
Sorry still not had time to take a proper look!

Hopefully during the week

**Comment by ciribob** [comment]
OK merged into branch ipAddressBook, found a weird bug. 

Changing the radio button doesnt change the model state even though its bound? 
Possibly this bug? https://social.msdn.microsoft.com/Forums/vstudio/en-US/8eb8280a-19c4-4502-8260-f74633a9e2f2/radiobutton-unchecked-bindings-issue-still-not-resolved?forum=wpf

Added a text input box back for autoconnect and for speed of quickly typing in an address

**Comment by GylesBates** [comment]
Hi Ciaran,

Ah interesting I'll take a look tomorrow night. It's probably because the address book view model doesn't implement IPropertyChanged and call raise property changed event.

Ah yeah, I wasn't sure about what to do with auto connect. I'll let you know

Gyles

On 7 Nov 2016 10:22 pm, "Ciaran Fisher" <notifications@github.com<mailto:notifications@github.com>> wrote:

OK merged into branch ipAddressBook, found a weird bug.

Changing the radio button doesnt change the model state even though its bound?
Possibly this bug? https://social.msdn.microsoft.com/Forums/vstudio/en-US/8eb8280a-19c4-4502-8260-f74633a9e2f2/radiobutton-unchecked-bindings-issue-still-not-resolved?forum=wpf

Added a text input box back for autoconnect and for speed of quickly typing in an address

**Pull request merged**
