### PR TITLE
Client Transmission Recording

### PR DESCRIPTION
**Pull request by JurgenvRooyen**
I've been playing around the last couple of days with a way to get audio recording working on the client side and have gotten it working. I don't think this is ready to be merged just yet but it does give a general idea for how I think an implementation might look, and I think its worth getting some feedback if it looks usable.

This approach does introduce a new dependency (NAudio.Lame), and includes a breaking change with an additional field in UDPPacket.

### CODE REVIEW

**Comment by ciribob** [comment]
I wouldnt want to change the packet structure as quite a few third parties use it
Instead - I would extend the SRClient to include a new flag that indicates if the user is OK with being recorded or not. If its a primitive bool it'll be false by default, so everyone on an older version is opted out, and anyone on a newer version has the choice

**Comment by JurgenvRooyen** [comment]
The changes to the packet structure have been reverted, and the bool flag for clients granting permission for recording is in SRClient.

There is a corner case with this current implementation, if a radio goes ~5.7 hours without an update it will end up with an array of samples greater than the limit of 2GB. Currently the way its being dealt with isn't ideal as it just breaks these up into multiple within max size arrays, so it'll dump 2GB+ into the write stream.

Also, apologies for build notification spam I forgot that I had already opened the draft PR.

**Comment by ciribob** [comment]
Sorry for the delay on this - can you see why the test is failing? Have you definitely reverted all your changes to the packet structure?

**Comment by JurgenvRooyen** [comment]
I was looking into that, unfortunately the last two weeks have been too busy to get stuck in. I'm hoping I'll have some time at the end of the week to pick this back up and get it all sorted.

**Comment by ciribob** [comment]
No worries at all - I'm away for a while moving house so no rush at all :)

Hope you have a good holiday break!

**Comment by JurgenvRooyen** [comment]
Found a bit of time today to get a bit more done. It looks like I messed something up when I reverted the UDPVoicePacket with git last time so that was an easy fix. Also added an arg for ExternalAudio for enabling recording (defaults to false).

I think currently that recording is working, but I the implementation isn't the best. Rather than the current method of storing all ClientAudio in a BlockingCollection and writing to streams only when there is data, continuously writing at regular intervals would be better, and avoids creating the condition for the corner case.

The drawback would be having to write every radio (including expansions) even if they're disabled, so for most users after every session there would be several empty MP3 files. 

I'd be happy to hear what others think would be a better choice between the two (or if they had a better solution) at this point.

**Comment by JurgenvRooyen** [comment]
I switched the audio processing to occur every two seconds and its working a lot better than the previous implementation, while avoiding the corner case completely.  

The RecordingManager class has also been refactored, to bring it down to a manageable size.

Added the ability to output to single file by mixing down audio.
Added UI elements to allow users to select if they want to save audio to one file, and select VBR quality.

Recording works in the limited testing I've been able to do, there does seem to be the odd crackle which I suspect is due to a discontinuity introduced when processing the samples but I haven't been able to find it.

Aside from some more testing, and refactoring if (I get some time) I think this is ready for review. This PR ended up being far larger than I intended so if you'd prefer this to be broken up that's doable.

Hope your move is going well, and hope you have a good new years.

**Comment by JurgenvRooyen** [comment]
Added a new class TransmissionAssembler to build audio sequentially, to help avoid DateTime.Now inaccuracy contributing to discontinuities.
Added option to play a tone in place of silence if a received transmission includes the client opting out of be recorded.

I haven't been able to resolve the discontinuity issue so while recording works the quality isn't perfect, and at this point I'm not able to find why its occurring.

**Comment by ciribob** [comment]
Each audio packet does have a packet number, you could try passing that through so you know which comes first and also of there are gaps.

That processing is all done by the jitter buffer before going to the mixdown for final output. Might give some inspiration?

Are you hearing the discontinuities on the normal output or only in the recording?

**Comment by JurgenvRooyen** [comment]
I'll have a look at the jitter buffer, that might give me a better clue on where to look.

There are discontinuities not present in the transmitted audio, though when I pass through a generated sine most of them disappear, so it might just be a case of hearing the captured audio in isolation makes it more noticeable. Apart from that every now and then the end of a buffer period (2 seconds) will have some discontinuity, and I'm not sure if its specific to some behavior of naudio.lame or my implementation. 

No problem on the wait, this has been a lot harder to implement than I had thought so most of the time has been used trying to work through some issues.

**Comment by JurgenvRooyen** [comment]
I put this on the backburner for a little too long, apologies.

You were right, I implemented reassembling the PCM data by packet number and that's resolved the audio quality issues I was having. Based on my testing I think recording is in an okay state, and ready reviewed.

**Comment by ciribob** [comment]
No need to apologise! I still need to sort a new release in general 😃
Thanks for this! Away on the weekend but I'll look at it soon

**Comment by ciribob** [comment]
Sorry just doing a quick release for the Apache - i'll work on getting this in next!

**Pull request merged**
