### PR TITLE
Initial commit for dotnet core

### PR DESCRIPTION
**Pull request by fedoracoreuser**
Hello, this is initial work to make the Common and Server components work under Linux, using .NET Core 6.0.
I would like this to be cross-platform, so that I could host more instances on a series of VMs, all on the same hardware and without all the associated licenses that Windows entails.

Basically, I added a new solution with two "shadow" project files. They reference the same source code as the main projects (minus a few files that are specific for .NET Framework 4.6.1), but by building under .NET Core they are multiplatform.

I am currently waiting on some work from the Open.NAT project, which currently uses .NET Framework but is scheduled to provide a Core version very soon.

I tested it locally, but there is further work to do before it's ready for inclusion. I have some experience on application porting to .NET Core, but I am by no means an expert.

Please let me know if this direction is acceptable for the project, or if there are other avenues you'd prefer to pursue, like completely separate codebases.

Thank you for all your work so far!

### CODE REVIEW

**Comment by ciribob** [comment]
Apologies for the incredibly slow reply!

This sounds like a very sensible approach and thank you very much !

If it's NAT that's blocking, I'm likely to remove it as its flakey (NAT it self) so I'd rather people just port forwarded.

Have a look at https://github.com/SimpleRadio/SRS-CalFire

This is a complete rewrite of SRS , .net core 6.0 and MVVM on the client too. Might have some bits worth stealing.

At some point I'll back port all these changes, and keep the network layer compatible (this version purposely isn't)

**Comment by fedoracoreuser** [comment]
Well, the OpenNAT project is slowly progressing on this: https://github.com/lontivero/Open.NAT/tree/netstd2
Particularly for the server environment target I was thinking of, removing it should not be a problem however.

I'll have a look at the project you linked and see what might be useful. Meanwhile, if you want, you can see if this MR works for you and if so, go ahead and include it.

Thank you!

**Comment by ciribob** [comment]
Closing this for now as I'm migrating the whole project to .net 6

I'll also likely make a command line server version for linux from this as well

**Comment by fedoracoreuser** [comment]
Great news! Thanks!

**Comment by ciribob** [comment]
No worries! see https://github.com/ciribob/DCS-SimpleRadioStandalone/tree/net-6-0-upgrade for progress

Sorry it took so long! Thanks for the initial PR as well

**Pull request closed without merging**
